// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfradecqsiqmqzxbjeyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mcmFkZWNxc2lxbXF6eGJqZXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTU4MDksImV4cCI6MjA2NzgzMTgwOX0.ERB9FShB5QNSYyeJ8teaqKZcg5b6hN10gBjKLUdNNeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});